import { CaseStudy } from './case-study.model';

/** Approved public editorial content based on James?s firsthand account. */
export const EXL_CASE_STUDY: CaseStudy = {
  title: 'EXL / LifePRO',
  introduction:
    'Senior Web Designer ? UX Engineering · Front-End Development · Accessibility · Product Design\n\nModernizing an established enterprise application without rewriting the world—combining UX, front-end development, accessibility, architecture, and pragmatic technical decision-making.',
  sections: [
    {
      heading: "The challenge wasn't starting over",
      paragraphs: [
        'LifePRO is an enterprise life-insurance policy administration platform.',
        'By the time I joined the work, it was a mature application with years of functionality, interconnected workflows, established users, and a substantial existing codebase.',
        'That changes the nature of product development.',
        "You aren't designing on a blank canvas. Every improvement has to coexist with what already works. A cleaner architecture isn't an improvement if getting there destabilizes the product. An accessibility fix isn't successful if it introduces thousands of new opportunities for regression.",
        'My official title was Senior Web Designer, but EXL hired me in part because I also brought front-end development experience to a product/design organization that needed those capabilities on the U.S. side of the team.',
        'My work therefore crossed UX, product design, accessibility, front-end development, and architecture.',
        "That combination became especially important as LifePRO's accessibility and technical-debt problems became increasingly difficult to solve within traditional role boundaries.",
      ],
    },
    {
      heading: 'I found the accessibility problem on day one',
      paragraphs: [
        "Accessibility wasn't something I discovered after LifePRO became a government-facing product.",
        'I raised it on my first day.',
        'Reviewing the existing application, I showed the team that the product was not meeting Section 508 requirements.',
        "At the time, that wasn't yet driving the product roadmap, but the underlying risk was already there.",
        'Later, EXL brought the U.S. Department of Veterans Affairs on as a client.',
        'I told the Senior Vice President responsible for the product that our existing accessibility issues were now going to have to be addressed.',
        "He wasn't initially convinced that they would become a requirement.",
        'They did.',
        'That led to a substantial Section 508 remediation initiative.',
        'I helped establish the blueprint for that work: identifying systemic accessibility problems, defining approaches for remediation, and helping engineering understand how those requirements translated into the existing front-end architecture.',
        'That progression—from identifying the problem before there was organizational pressure to fix it, to helping shape the remediation effort when it became a business requirement—is one of the most important parts of my LifePRO work.',
      ],
    },
    {
      heading: '1.5 million lines of html — or about 150 lines of sass',
      paragraphs: [
        'One systemic accessibility problem captured my approach particularly well.',
        'The proposed solution would have required changes across roughly 1.5 million lines of existing HTML.',
        'Technically, that could have been done.',
        'But before accepting a rewrite of that scale, I traced the behavior through the presentation layer to understand why the problem existed everywhere in the first place.',
        'The defect was systemic.',
        'I believed the solution could be systemic too.',
        "The development team didn't believe the approach I was proposing would work.",
        'So I stepped outside the normal boundaries of my design role and built it myself.',
        'With roughly 150 lines of Sass, I demonstrated that this particular systemic presentation problem could be corrected without touching approximately 1.5 million lines of markup.',
        'That proof changed the conversation.',
        "It wasn't theoretical anymore.",
        'There was working code.',
        "The important number isn't really 150.",
        "It's the difference between asking:",
        '“How do we change every place this problem appears?”',
        'and:',
        '“Why does this problem appear everywhere?”',
        "Sass wasn't a substitute for semantic accessibility. It was the correct layer for this particular systemic presentation problem.",
        "The best fix wasn't the biggest fix.",
        'It was the one applied at the right layer.',
      ],
    },
    {
      heading: 'Why design + development mattered',
      paragraphs: [
        'That experience also illustrates why having development capability inside the product/design organization mattered.',
        'I could move from identifying a UX or accessibility problem, to examining the implementation, to writing the code necessary to prove a different solution was possible.',
        "A design handed to engineering as a picture isn't finished.",
        'Interaction behavior, semantics, keyboard access, responsive behavior, component constraints, edge cases, styling architecture, and business rules all emerge during implementation.',
        'Being able to work on both sides of that boundary meant I could stay involved when those decisions were actually being made.',
        'Sometimes that meant designing.',
        'Sometimes it meant working directly with developers.',
        'And sometimes it meant opening the code editor and proving the idea myself.',
      ],
    },
    {
      heading: 'Designing enterprise workflows',
      paragraphs: [
        "My work wasn't limited to the technical foundation.",
        'I designed approximately 40% of the screens and workflows introduced across LifePRO versions 20 and 21.',
        'Enterprise insurance software is information-dense by necessity.',
        'Users work with interconnected processes, business rules, policy data, and decisions that can have consequences far beyond a single screen.',
        "The challenge isn't making that complexity disappear.",
        "It's deciding what the user needs now, what can wait, how information should be grouped, how actions relate to the task, and how the interface communicates what the system is doing.",
        'That required moving continuously between UX and implementation—from workflows and prototypes through the HTML, component behavior, styling, keyboard interaction, and accessibility details that determined what users actually received.',
      ],
    },
    {
      heading: 'Accessibility as engineering',
      paragraphs: [
        "Section 508 wasn't something we could check after development.",
        'It affected design decisions, component behavior, keyboard interaction, semantics, styling, and the way we evaluated third-party UI components.',
        "PrimeNG provided useful components, but using a component library doesn't transfer responsibility for accessibility to the library vendor.",
        "When component behavior didn't meet our requirements, we investigated and corrected it rather than treating the framework as untouchable.",
        "That reinforced a lesson I've carried into later work:",
        'Accessibility problems are often engineering problems.',
        'Sometimes the answer is markup.',
        "Sometimes it's interaction design, focus management, CSS, component architecture, or assumptions embedded in a third-party dependency.",
        'The job is to find the actual cause.',
      ],
    },
    {
      heading: 'Modernization — and the technical debt underneath it',
      paragraphs: [
        'LifePRO was still running Angular 7 when I left EXL.',
        "I investigated the application's modernization path and worked locally through newer Angular versions, eventually getting a local branch to compile and build through Angular 10.",
        'But compiling successfully was only part of the problem.',
        'The upgraded UI was not production-ready.',
        'The migration exposed deeper technical debt in the existing front end, particularly accumulated Bootstrap markup and Sass structure.',
        'The framework could be moved forward.',
        'The existing presentation architecture could not simply follow it without substantial refactoring.',
        'That distinction mattered.',
        'Sometimes modernization proves that the framework itself is the problem.',
        'Other times a framework upgrade exposes architectural problems the existing version had been hiding.',
        "In LifePRO's case, the migration work reinforced something I was already seeing elsewhere: portions of the front end ultimately needed substantial HTML and styling refactoring.",
        'That technical debt had repeatedly been deferred, and the broader refactor was not undertaken during my time on the product.',
        "The local modernization work therefore wasn't a production migration success story.",
        'It was architectural evidence.',
        "It demonstrated that simply upgrading Angular wasn't enough; the application also had to address the front-end debt accumulated underneath it.",
      ],
    },
    {
      heading: 'Looking for systems, not symptoms',
      paragraphs: [
        'The 1.5-million-line accessibility problem was the most dramatic example, but the same reasoning applied throughout the application.',
        "When the same defect appeared repeatedly, I didn't want twenty local fixes if one shared cause explained all twenty.",
        'When a component behaved incorrectly, I wanted to know whether the problem belonged to our implementation, shared styling, application architecture, or the component library itself.',
        "And when modernization exposed technical debt, the goal wasn't simply to make the immediate error disappear.",
        'It was to understand what the error was telling us about the system.',
        'That approach allowed me to contribute beyond individual screens: identifying systemic front-end problems, advising on UX and accessibility decisions, and helping establish patterns engineers could reuse instead of rediscovering the same solutions.',
      ],
    },
    {
      heading: 'Working from implementation to executive leadership',
      paragraphs: [
        'LifePRO was built across specialties, organizations, and time zones.',
        'I worked directly with designers, developers, product managers, business analysts, and offshore engineers in Noida, India.',
        'I also worked directly with senior product leadership, including Senior Vice Presidents.',
        'My management chain placed the work close to executive technology leadership: my manager reported to the CTO, who reported to the CEO.',
        'EXL was a Fortune 500 company.',
        'That meant being able to discuss the same problem at very different levels—from the CSS or component behavior causing an accessibility defect, to the product risk and customer requirement that made fixing it important.',
        'Being able to speak both UX and engineering also made those conversations easier to carry through implementation.',
        "I wasn't simply handing designs across an organizational boundary.",
        'I could help connect product intent, accessibility requirements, design decisions, and the code required to deliver them.',
      ],
    },
    {
      heading: 'What this work demonstrates',
      paragraphs: [
        'LifePRO taught me that maintaining a mature enterprise product requires a different kind of judgment than building something new from scratch.',
        'Sometimes progress means designing a new workflow.',
        "Sometimes it means proving an implementation everyone else thinks won't work.",
        'Sometimes it means recognizing a customer requirement before it reaches the roadmap.',
        "Sometimes an attempted framework upgrade tells you that the real problem isn't the framework at all.",
        'And sometimes the most valuable contribution is recognizing that a proposed rewrite of roughly 1.5 million lines is really a 150-line problem hiding at the wrong architectural layer.',
        "That's the work I enjoy most:",
        'Finding the leverage point where UX, accessibility, product thinking, and engineering meet—and solving the underlying problem instead of multiplying the symptoms.',
      ],
    },
    {
      heading: 'Core technologies and practices',
      items: [
        'Angular',
        'TypeScript',
        'JavaScript',
        'HTML5',
        'Sass/CSS',
        'PrimeNG',
        'Bootstrap',
        'Section 508',
        'WCAG',
        'Accessibility Engineering',
        'Enterprise UX',
        'Responsive Design',
        'Front-End Architecture',
        'Figma',
        'Justinmind',
        'Prototyping',
        'Component Architecture',
        'Cross-Functional Collaboration',
        'Distributed Development',
      ],
    },
  ],
};
